parameters:
  - name: build
    type: jobList
    default: []
  - name: pool
    type: object
    default:
      vmImage: ubuntu-latest
  - name: manifests
    type: string
    default: ./manifests
  - name: containers
    type: string
    default: ""
  - name: staging
    type: object
    default:
      environment: null
      namespace: null
      healthcheck: null
  - name: production
    type: object
    default:
      environment: null
      namespace: null
      healthcheck: null

stages:
- stage: build
  displayName: Build
  pool: ${{ parameters.pool }}
  jobs:  
    - ${{ parameters.build }}

    - job: package_manifests
      displayName: Package Manifests
      steps:
        - publish: ${{ parameters.manifests }}
          artifact: manifests

- stage: deploy_staging
  displayName: Deploy (Staging)
  pool: ${{ parameters.pool }}
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn:
    - build
  jobs:
    - deployment: deploy_staging
      displayName: Deploy Staging
      environment: ${{ parameters.staging.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
              - task: KubernetesManifest@0
                name: deploy
                displayName: Deploy 
                inputs:
                  action: deploy
                  namespace: ${{ parameters.staging.namespace }}
                  manifests: $(Pipeline.Workspace)/manifests/*.yml

                  containers: ${{ parameters.containers }}
          postRouteTraffic:
            steps:
              - ${{ if parameters.staging.healthcheck }}:
                - pwsh: |
                        $retries = 5
                        $interval = 10

                        while ($retries -gt 0) {
                            $retries -= 1
                            
                            $resp = Invoke-WebRequest -Uri $env:endpoint -Method Get -SkipHttpErrorCheck
                            Write-Host "Received HTTP ${resp.StatusCode} ${resp.StatusDescription} ($retries retries remaining)"
                            Write-Host $resp.Content
                            
                            if (($resp.StatusCode -ge 200) -and ($resp.StatusCode -le 299)) {
                                exit 0
                            }
                            
                            Start-Sleep -Seconds $interval
                        }

                        exit 1

                  env:
                    endpoint: ${{ parameters.staging.healthcheck }}

- stage: deploy_prod
  displayName: Deploy (Production)
  pool: ${{ parameters.pool }}
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn:
    - build
    - deploy_staging
  jobs:
    - deployment: deploy_prod
      displayName: Deploy Production
      environment: ${{ parameters.production.environment }}
      strategy:
        runOnce:
          deploy:
            steps:
              - task: KubernetesManifest@0
                name: deploy
                displayName: Deploy 
                inputs:
                  action: deploy
                  namespace: ${{ parameters.production.namespace }}
                  manifests: $(Pipeline.Workspace)/manifests/*.yml
                  containers: ${{ parameters.containers }}
          postRouteTraffic:
            steps:
              - ${{ if parameters.production.healthcheck }}:
                - pwsh: |
                        $retries = 5
                        $interval = 10

                        while ($retries -gt 0) {
                            $retries -= 1
                            
                            $resp = Invoke-WebRequest -Uri $env:endpoint -Method Get -SkipHttpErrorCheck
                            Write-Host "Received HTTP ${resp.StatusCode} ${resp.StatusDescription} ($retries retries remaining)"
                            Write-Host $resp.Content
                            
                            if (($resp.StatusCode -ge 200) -and ($resp.StatusCode -le 299)) {
                                exit 0
                            }
                            
                            Start-Sleep -Seconds $interval
                        }

                        exit 1

                  env:
                    endpoint: ${{ parameters.production.healthcheck }}